apiVersion: apps/v1
kind: Deployment
metadata:
  name: yellow-color
spec:
  replicas: 2
  selector:
    matchLabels:
      app: yellow-color
  template:
    metadata:
      labels:
        app: yellow-color
        color-group: mixed
    spec:
      containers:
      - name: yellow
        image: sbeliakou/color:v1
        env:
        - name: COLOR
          value: yellow
        ports:
        - containerPort: 8080
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: yellow-svc
spec:
  selector:
    app: yellow-color
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: green-color
spec:
  replicas: 1
  selector:
    matchLabels:
      app: green-color
  template:
    metadata:
      labels:
        app: green-color
        color-group: mixed
    spec:
      containers:
      - name: green
        image: sbeliakou/color:v1
        env:
        - name: COLOR
          value: green
        ports:
        - containerPort: 8080
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: green-svc
spec:
  selector:
    app: green-color
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: red-color
spec:
  replicas: 3
  selector:
    matchLabels:
      app: red-color
  template:
    metadata:
      labels:
        app: red-color
        color-group: mixed
    spec:
      containers:
      - name: red
        image: sbeliakou/color:v1
        env:
        - name: COLOR
          value: red
        ports:
        - containerPort: 8080
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: red-svc
spec:
  selector:
    app: red-color
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: lights-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: lights.k8slab.net
    http:
      paths:
      - path: /red
        pathType: Prefix
        backend:
          service:
            name: red-svc
            port:
              number: 8080
      - path: /green
        pathType: Prefix
        backend:
          service:
            name: green-svc
            port:
              number: 8080
      - path: /yellow
        pathType: Prefix
        backend:
          service:
            name: yellow-svc
            port:
              number: 8080
      - path: /
        pathType: Prefix
        backend:
          service:
            name: switch
            port:
              number: 80
---
apiVersion: v1
kind: Service
metadata:
  name: switch
spec:
  selector:
    color-group: mixed
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  type: ClusterIP
